cmd_drivers/net/wireless/mt_soc/conn_soc/mt_wifi/wlan/os/linux/hif/ahb/arm.o := /opt/buildroot-gcc483_arm/usr/bin/arm-linux-gcc -Wp,-MD,drivers/net/wireless/mt_soc/conn_soc/mt_wifi/wlan/os/linux/hif/ahb/.arm.o.d  -nostdinc -isystem /opt/buildroot-gcc483_arm/usr/lib/gcc/arm-buildroot-linux-uclibcgnueabi/4.8.3/include -I/home/mt7623/MTKSDK/5.0.2.0/MTK_APSoC_SDK/source/linux-3.10.20.x/arch/arm/include -Iarch/arm/include/generated  -Iinclude -I/home/mt7623/MTKSDK/5.0.2.0/MTK_APSoC_SDK/source/linux-3.10.20.x/arch/arm/include/uapi -Iarch/arm/include/generated/uapi -I/home/mt7623/MTKSDK/5.0.2.0/MTK_APSoC_SDK/source/linux-3.10.20.x/include/uapi -Iinclude/generated/uapi -include /home/mt7623/MTKSDK/5.0.2.0/MTK_APSoC_SDK/source/linux-3.10.20.x/include/linux/kconfig.h -D__KERNEL__ -mlittle-endian -Iarch/arm/mach-mt7623/include -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -fno-delete-null-pointer-checks -O2 -fno-dwarf2-cfi-asm -fno-omit-frame-pointer -mapcs -mno-sched-prolog -fstack-protector -mabi=aapcs-linux -mno-thumb-interwork -marm -D__LINUX_ARM_ARCH__=7 -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -Uarm -Wframe-larger-than=1024 -Wno-unused-but-set-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -DCC_HAVE_ASM_GOTO -D MTK_WCN_REMOVE_KERNEL_MODULE -DLINUX -DMT6628 -DCFG_SUPPORT_WAPI=0 -DCFG_SUPPORT_XLOG=1 -DCFG_SUPPORT_AEE=0 -DCFG_SUPPORT_HOTSPOT_2_0=0 -DCFG_HS20_DEBUG=0 -DCFG_ENABLE_GTK_FRAME_FILTER=0 -D_HIF_SDIO=1 -DDBG=0 -Idrivers/net/wireless/mt_soc/conn_soc/mt_wifi/wlan/os -Idrivers/net/wireless/mt_soc/conn_soc/mt_wifi/wlan/os/linux/include -Idrivers/net/wireless/mt_soc/conn_soc/mt_wifi/wlan/os/linux/hif/ahb/include -Idrivers/net/wireless/mt_soc/conn_soc/mt_wifi/wlan/include -Idrivers/net/wireless/mt_soc/conn_soc/mt_wifi/wlan/include/nic -Idrivers/net/wireless/mt_soc/conn_soc/mt_wifi/wlan/include/mgmt -I/home/mt7623/MTKSDK/5.0.2.0/MTK_APSoC_SDK/source/linux-3.10.20.x/arch/arm/mach-mt7623/fpga7623_emmc/dct    -D"KBUILD_STR(s)=\#s" -D"KBUILD_BASENAME=KBUILD_STR(arm)"  -D"KBUILD_MODNAME=KBUILD_STR(wlan_mt)" -c -o drivers/net/wireless/mt_soc/conn_soc/mt_wifi/wlan/os/linux/hif/ahb/arm.o drivers/net/wireless/mt_soc/conn_soc/mt_wifi/wlan/os/linux/hif/ahb/arm.c

source_drivers/net/wireless/mt_soc/conn_soc/mt_wifi/wlan/os/linux/hif/ahb/arm.o := drivers/net/wireless/mt_soc/conn_soc/mt_wifi/wlan/os/linux/hif/ahb/arm.c

deps_drivers/net/wireless/mt_soc/conn_soc/mt_wifi/wlan/os/linux/hif/ahb/arm.o := \

drivers/net/wireless/mt_soc/conn_soc/mt_wifi/wlan/os/linux/hif/ahb/arm.o: $(deps_drivers/net/wireless/mt_soc/conn_soc/mt_wifi/wlan/os/linux/hif/ahb/arm.o)

$(deps_drivers/net/wireless/mt_soc/conn_soc/mt_wifi/wlan/os/linux/hif/ahb/arm.o):
